kind: Service
apiVersion: v1
metadata:
  name: grafana-ingress
  labels:
    app: grafana-ingress
spec:
  ports:
    - name: http
      nodePort: 32746
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.19
