apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pihole-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pihole/etc-pihole"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: etc-pihole-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-dnsmasq.d-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pihole/etc-dnsmasq.d"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-dnsmasq.d-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: etc-dnsmasq.d-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  volumes:
    - name: etc-pihole
      persistentVolumeClaim:
        claimName: etc-pihole-pvc
    - name: etc-dnsmasq
      persistentVolumeClaim:
        claimName: etc-dnsmasq.d-pvc
  containers:
    - name: pihole
      image: pihole/pihole
      ports:
      - containerPort: 80
        name: http
      - containerPort: 53
        name: dns
      - containerPort: 67
        name: dhcp
      volumeMounts:
      - name: etc-pihole
        mountPath: /etc/pihole
      - name: etc-dnsmasq
        mountPath: /etc/dnsmasq.d
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-tcp
  labels:
    app: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns
      port: 53
      targetPort: 53
      protocol: TCP
  selector:
    app: pihole
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.24
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-udp
  labels:
    app: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dhcp
      port: 67
      targetPort: 67
      protocol: UDP
  selector:
    app: pihole
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.24
