apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/homelab/unifi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: unifi-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: unifi
  labels:
    app: unifi
spec:
  volumes:
  - name: unifi-config
    persistentVolumeClaim:
      claimName: unifi-pvc
  containers:
    - name: unifi
      image: ghcr.io/linuxserver/unifi-controller
      volumeMounts:
      - name: unifi-config
        mountPath: /config
      ports:
      - containerPort: 8080
        name: http
      - containerPort: 8443
        name: https
      - containerPort: 6789
        name: speedtest
      - containerPort: 3478
        name: stun
      - containerPort: 10001
        name: discovery
      volumeMounts:
      - mountPath: "/config"
        name: unifi-config
---
kind: Service
apiVersion: v1
metadata:
  name: unifi-tcp
  labels:
    app: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: speedtest
      port: 6789
      targetPort: 6789
      protocol: TCP
  selector:
    app: unifi
  type: LoadBalancer
  loadBalancerIP: 192.168.1.17
  externalTrafficPolicy: Cluster
---
kind: Service
apiVersion: v1
metadata:
  name: unifi-udp
  labels:
    app: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi"
spec:
  ports:
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: discovery
      port: 10001
      targetPort: 10001
      protocol: UDP
  selector:
    app: unifi
  type: LoadBalancer
  loadBalancerIP: 192.168.1.17
  externalTrafficPolicy: Cluster
