apiVersion: v1
kind: Pod
metadata:
  name: dvwa
  labels:
    app: dvwa
spec:
  containers:
    - name: dvwa
      image: vulnerables/web-dvwa
      ports:
      - containerPort: 80
        name: http
---
kind: Service
apiVersion: v1
metadata:
  name: dvwa
  labels:
    app: dvwa
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dvwa
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.23
