apiVersion: v1
kind: PersistentVolume
metadata:
  name: bamboo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/homelab/bamboo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bamboo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: bamboo-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: bamboo
  labels:
    app: bamboo
spec:
  volumes:
    - name: bamboo
      persistentVolumeClaim:
        claimName: bamboo-pvc
  containers:
    - name: bamboo
      image: atlassian/bamboo
      env:
      - name: ATL_BROKER_CLIENT_URI
        value: "tcp://192.168.1.26:54663?wireFormat.maxInactivityDuration=300000"
      - name: ATL_JDBC_URL
        value: "jdbc:postgresql://postgres:5432/bamboo"
      - name: ATL_JDBC_USER
        value: "postgres"
      - name: ATL_JDBC_PASSWORD
        value: "postgres"
      ports:
      - containerPort: 8085
        name: bamboo-tomcat
      - containerPort: 54663
        name: bamboo-broker
      volumeMounts:
      - name: bamboo
        mountPath: /var/atlassian/application-data/bamboo
---
kind: Service
apiVersion: v1
metadata:
  name: bamboo
  labels:
    app: bamboo
spec:
  ports:
    - name: bamboo-tomcat
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: bamboo-broker
      port: 54663
      targetPort: 54663
      protocol: TCP
  selector:
    app: bamboo
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.26
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/homelab/bamboo-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: postgres-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
    - name: postgres
      persistentVolumeClaim:
        claimName: postgres-pvc
  containers:
    - name: postgres
      image: postgres
      env:
      - name: POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_DB
        value: "bamboo"
      - name: PGDATA
        value: "/var/lib/postgresql/data/pgdata"
      volumeMounts:
      - name: postgres
        mountPath: /var/lib/postgresql/data
      ports:
      - containerPort: 5432
        name: postgres
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
  type: ClusterIP
