apiVersion: v1
kind: PersistentVolume
metadata:
  name: statping-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/statping-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statping-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: statping-mysql-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: statping-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/statping"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statping-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: statping-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: statping
  labels:
    app: statping
spec:
  volumes:
  - name: statping-config
    persistentVolumeClaim:
      claimName: statping-pvc
  containers:
    - name: statping
      image: statping/statping
      volumeMounts:
      - name: statping-config
        mountPath: /app
      ports:
      - containerPort: 8080
        name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: statping-mysql
  labels:
    app: statping-mysql
spec:
  volumes:
  - name: statping-mysql-data
    persistentVolumeClaim:
      claimName: statping-mysql-pvc
  containers:
    - name: statping-mysql
      image: mysql
      volumeMounts:
      - name: statping-mysql-data
        mountPath: /var/lib/mysql
      env:
      - name: MYSQL_USER
        value: "mysql"
      - name: MYSQL_PASSWORD
        value: "mysql"
      - name: MYSQL_DATABASE
        value: "statping"
      - name: MYSQL_ROOT_PASSWORD
        value: "mysql"
      ports:
      - containerPort: 3306
        name: mysql
---
kind: Service
apiVersion: v1
metadata:
  name: statping
  labels:
    app: statping
  annotations:
    metallb.universe.tf/allow-shared-ip: "statping"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: statping
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.20
---
kind: Service
apiVersion: v1
metadata:
  name: statping-mysql
  labels:
    app: statping-mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: "statping"
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: statping-mysql
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.20
